import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Myprofile from "@/component/myprofile";
import Navbar from "@/component/navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "my resume",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-gray-800">
        <div className="bg-[url('/image/bg.webp')] bg-cover bg-center bg-no-repeat w-full min-h-screen">
          <div className="grid grid-cols-12 gap-4">  
          <div className="col-span-12 md:col-span-5 lg:col-span-4">
            <Myprofile />
          </div>
          <div className="col-span-12 md:col-span-7 lg:col-span-8">
            <Navbar />
            <div className=" bg-white/80 p-5">
              {children}
            </div>
          </div>
        </div>
        </div>
      </body>
    </html>
  );
}
